### ISSUE TITLE
set_key= is incompatible with OpenSSL 3.0

### ISSUE THREAD

**Issue by janoschp** [PexegoUva/rails_apple_signin#3]
Please update your dependencies, this issue was fixed when I checked out your project and updated jwt to the latest version.

I'm getting this error lately when users try to register with Apple:

[cb1e599a-4137-4fdb-b348-b36bf64e9423] OpenSSL::PKey::PKeyError (rsa#set_key= is incompatible with OpenSSL 3.0):
[cb1e599a-4137-4fdb-b348-b36bf64e9423]   
[cb1e599a-4137-4fdb-b348-b36bf64e9423] config/initializers/doorkeeper.rb:21:in `block (2 levels) in <main>'
[cb1e599a-4137-4fdb-b348-b36bf64e9423] app/controllers/tokens_controller.rb:7:in `create'
[cb1e599a-4137-4fdb-b348-b36bf64e9423] lib/middleware/healthcheck.rb:17:in `call'

It has to do with the way you verify Apple's public keys and this bug: https://github.com/jwt/ruby-jwt/issues/495

When updating to the latest version of jwt:   spec.add_runtime_dependency 'jwt', '~> 2.7' this bug is resolved.

**Comment by matas-zanevicius** [comment]
@PexegoUva please issue a new version to include this fix 🙏

**Comment by antonengelhardt** [comment]
+1

**Comment by jndrkmllh** [comment]
same issue here

**Comment by antonengelhardt** [comment]
@matas-zanevicius You can get the changes from master branch.

```
gem 'apple_id_token', git: 'https://github.com/PexegoUva/rails_apple_signin', branch: 'master'
```

However, a new release would be awesome!

**Comment by PexegoUva** [comment]
Hey guys. I have issued a new release `0.4.0` pointing to `master`. Just to let you know that I am not longer supporting Ruby developments, and in this case this library so feel free to fork it and continue with the development in case you need it!!

Thank you all and sorry for being late.

**Comment by antonengelhardt** [comment]
> Hey guys. I have issued a new release `0.4.0` pointing to `master`. Just to let you know that I am not longer supporting Ruby developments, and in this case this library so feel free to fork it and continue with the development in case you need it!!
> 
> 
> 
> Thank you all and sorry for being late.

Thanks for pointing out and doing another release!

Might it be a good idea to put a note in the Readme that this project is not under active maintenance?
